### ISSUE TITLE
Commas in RGB format

### ISSUE THREAD

**Issue by JavierM42** [sindresorhus/hex-rgb#19]
I noticed there are no commas in the RGB format, which could be a nice feature. Is there a reason for that?

I specifically needed the commas and ended up doing this, which wasn't too elegant.

```
      const HEX = '#FF0000';
      const C = hexRgb(HEX);
      const RGB = `rgb(${C.red}, ${C.green}, ${C.blue})`;
```

**Comment by sindresorhus** [comment]
The modern format is without commas. I have no plans to add commas. https://dev.to/alvaromontoro/the-ultimate-guide-to-css-colors-2020-edition-1bh1
