### ISSUE TITLE
Compile time error in TS

### ISSUE THREAD

**Issue by shelterit** [sindresorhus/hex-rgb#20]
Just installed it, and got this;

```
ERROR in ../node_modules/hex-rgb/index.d.ts:31:5 - error TS1005: ',' expected.

31  red: number,
       ~
../node_modules/hex-rgb/index.d.ts:32:7 - error TS1005: ',' expected.

32  green: number,
         ~
../node_modules/hex-rgb/index.d.ts:33:6 - error TS1005: ',' expected.

33  blue: number,
        ~
../node_modules/hex-rgb/index.d.ts:34:7 - error TS1005: ',' expected.

34  alpha: number
         ~
```

Not sure what this is, if it's a ts-lint thing, or version compatibility? 

TS 4.2.4, ES6, lib es2017

**Comment by sindresorhus** [comment]
> Just installed it, and got this;

It doesn't sound like you have done any effort to try to debug this yourself.

**Comment by sindresorhus** [comment]
The syntax referenced in the error message is named tuple elements and are available since TS 4. I'm going to close as this package is tested against TypeScript, so I doubt it's anything wrong with the types here. Happy to reopen if you provide a failing test.
