### ISSUE TITLE
Can this work with regular require?

### ISSUE THREAD

**Issue by abbott567** [sindresorhus/hex-rgb#21]
Hi, is there a way to get this working like a regular `module.exports` and `require`?

Tried unsuccessfully with the following:
```javascript
const hexrgb = require('hex-rgb');

const { hexrgb } = require('hex-rgb');

const hexrgb = require('hex-rgb').default;
```

Thanks

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
