### ISSUE TITLE
Alpha should be a float

### ISSUE THREAD

**Issue by nmccready** [sindresorhus/hex-rgb#3]
Curious why the returned alpha value is not divided by 255? Just by looking at the code the returned number is still relative to hex and not an alpha percentage / fraction as inputed by rgb-hex.

**Comment by sindresorhus** [comment]
That's a good point. I didn't notice that when merging the PR adding it. I think it should indeed be changed to be a fraction.

**Comment by nmccready** [comment]
gracias
