### ISSUE TITLE
Not compatible with default webpack production build

### ISSUE THREAD

**Issue by penx** [sindresorhus/hex-rgb#4]
If you have a module, index.js, that has hex-rgb as a dependency, and run the following:

`webpack -p src/index.js --output-filename dist/index.js`

(without any additional webpack config)

This will fail because the default webpack production settings uses Uglify2, which [does not support ES6 template strings](https://github.com/mishoo/UglifyJS2/issues/950).

Could this module distribute a lib version that has been transpiled and is therefore compatible with uglify2/default webpack cli settings?

**Comment by penx** [comment]
Alternatively, if users that require an ES5 compatible version should use v1, perhaps add this to the readme?

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.
