### ISSUE TITLE
Output to text

### ISSUE THREAD

**Issue by zbynekrybicka** [sindresorhus/hex-rgb#8]
Hi, I would like to add option for text output from hex. I made it. However I can't make the PR. Can you enable me?

**Comment by sindresorhus** [comment]
What would the text output look like?

**Comment by sindresorhus** [comment]
> However I can't make the PR. Can you enable me?

There's nothing to enable. Your able to open an issue, so you're able to open a PR too.

**Comment by zbynekrybicka** [comment]
Ok. I said wrong. I can't push new branch. Logs to me Permission denied

**Comment by zbynekrybicka** [comment]
Sorry. I did it first time... PR is created.

**Comment by zbynekrybicka** [comment]
Excuse me, please. Can you give me feedback?
